### ISSUE TITLE
will the code be open-sourcing

### ISSUE THREAD

**Issue by ab1412** [robincourant/jaws#2]
Hi robincourant,

I'm really impressed by your work. Any chance you'll be open-sourcing the code soon? I'd love to learn from it and apply the techniques in my projects.

Thanks

**Comment by robincourant** [comment]
Hi ab1412,

Thanks for your interest in our work! We're actively working on open-sourcing the code, and it will be available soon (in the next few weeks). Keep an eye on our GitHub repository for updates.
