### ISSUE TITLE
How to construct a dataset like jaws

### ISSUE THREAD

**Issue by CrisZhouh** [robincourant/jaws#3]
I found that there is a data/jaws_dolly_zoom_mask/saved_data.pk, how is it built, and how can I generate this saved_data.pk file if I want to use other film pics

**Comment by robincourant** [comment]
Hi, 
Thanks for your interest in you work. The `saved_data.pk` corresponds to the JAWS's output file (i.e. poses in the NeRF scene). We only use images from movies, no camera poses.
